# based on: https://github.com/Synthetixio/synthetix/blob/develop/.github/workflows/slither-analysis.yml
name: Slither for packages/synthetix-main

on:
  push:
  pull_request:
    branches: [master, develop]

jobs:
  slither:
    name: Slither Analysis
    # run only on master/develop branch and pull requests
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2

      - name: Set npm cache directory
        run: npm config set cache .npm-cache --global
        continue-on-error: true

      - uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # pin@v2
        with:
          path: |
            .npm-cache
            node_modules
          key: ${{ runner.os }}-ubuntu-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-ubuntu-
        continue-on-error: true

      - name: Install dependencies
        run: npm install --prefer-offline

      - name: Run slither
        run: npm run slither-sarif --workspace=packages/synthetix-main || true

      - name: Upload lint results
        if: always()
        uses: github/codeql-action/upload-sarif@7112cdaa06f3b661965fe3e2e93c9acaadbe85f3 # pin@codeql-bundle-20210921
        with:
          sarif_file: packages/synthetix-main/slither.sarif
        continue-on-error: true
